version: '3.7'
services:
  chiclets-app:
    build:
      context: .
      dockerfile: docker/php8-apache/Dockerfile
      args:
        - APACHE_DOCUMENT_ROOT=${DOCKER_APP_APACHE_DOCUMENT_ROOT}
        - HOST_USER_ID=${DOCKER_HOST_USER_ID}
    environment:
      - XDEBUG_MODE=${DOCKER_APP_XDEBUG_MODE}
      - XDEBUG_CONFIG=client_host=${DOCKER_APP_XDEBUG_CLIENT_HOST} client_port=${DOCKER_APP_XDEBUG_CLIENT_PORT}
      - XDEBUG_SESSION=1
      - PHP_IDE_CONFIG=serverName=chiclets-app
    volumes:
      - './../:/var/www/html'
    ports:
      - '${DOCKER_APP_HOST_PORT}:80'
    extra_hosts:
      - host.docker.internal:host-gateway
  chiclets-mysql:
    build: docker/mysql
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DOCKER_MYSQL_DATABASE}
      MYSQL_USER: ${DOCKER_MYSQL_USER}
      MYSQL_PASSWORD: ${DOCKER_MYSQL_PASSWORD}
    ports:
      - '${DOCKER_MYSQL_HOST_PORT}:3306'

